# Generated by Django 3.1.7 on 2021-03-11 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='staus',
            new_name='status',
        ),
    ]
