# Generated by Django 3.1.7 on 2021-03-13 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_bookinstance_borrower'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='book',
            new_name='books',
        ),
    ]
